# 02 Tensor Basics

In [1]:
import torch

## Creation

In [2]:
torch.empty(2, 3)

tensor([[8.4078e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [3]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.ones(2, 3, dtype=torch.int)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [5]:
x = torch.ones(2, 3, dtype=torch.int)
x.size(), x.dtype

(torch.Size([2, 3]), torch.int32)

In [6]:
torch.tensor([2.5, 0.1, 3])

tensor([2.5000, 0.1000, 3.0000])

## Operations

In [7]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
x + y

tensor([[1.3513, 0.6364],
        [1.1386, 0.7365]])

In [8]:
y.add_(x)
y

tensor([[1.3513, 0.6364],
        [1.1386, 0.7365]])

In [9]:
x = torch.rand(4, 4)
x[:, 0]

tensor([0.8188, 0.1155, 0.1623, 0.7558])

In [10]:
x[1, 1].item()

0.03958284854888916

In [11]:
x.view(16)

tensor([0.8188, 0.5932, 0.6917, 0.2505, 0.1155, 0.0396, 0.1684, 0.0936, 0.1623,
        0.3715, 0.1074, 0.7030, 0.7558, 0.4723, 0.4792, 0.9168])

In [12]:
x.view(-1, 8)

tensor([[0.8188, 0.5932, 0.6917, 0.2505, 0.1155, 0.0396, 0.1684, 0.0936],
        [0.1623, 0.3715, 0.1074, 0.7030, 0.7558, 0.4723, 0.4792, 0.9168]])

## From NumPy

In [13]:
import numpy as np

In [14]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [15]:
a.add_(1)
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [16]:
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [17]:
a += 1
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

## Device

Apple Silicon

In [18]:
torch.has_mps

True

In [19]:
device = torch.device('mps')
device

device(type='mps')