# 03 Autograd

In [1]:
import torch

In [2]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.4846,  0.3363, -0.3814], requires_grad=True)

In [4]:
y = x + 2
y

tensor([2.4846, 2.3363, 1.6186], grad_fn=<AddBackward0>)

In [5]:
z = y * y * 2
z

tensor([12.3462, 10.9163,  5.2399], grad_fn=<MulBackward0>)

In [6]:
z = z.mean()
z

tensor(9.5008, grad_fn=<MeanBackward0>)

In [7]:
z.backward()

In [8]:
x.grad

tensor([3.3128, 3.1150, 2.1582])

## Prevent grad tracking

In [9]:
x.requires_grad_(False)
x

tensor([ 0.4846,  0.3363, -0.3814])

In [10]:
x.requires_grad_(True)
x_ = x.detach()
x_

tensor([ 0.4846,  0.3363, -0.3814])

In [12]:
with torch.no_grad():
    y = x + 2 
    print(y)

tensor([2.4846, 2.3363, 1.6186])


## Dummy Example

In [14]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
    model_output = (weights * 3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
